services:
  # Backend Service
  - type: web
    name: didadoeback
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://didadoe.onrender.com

  # Frontend Service  
  - type: web
    name: didadoe
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://didadoeback.onrender.com